export default {
    // logo: require('./logo.png'),
    // background: require('./background.jpg'),
    // placeholderImage: require('./placeholder.png'),
    painting: require('./painting/Painting1.jpeg'),
    fantasy: require('./fantasy/Fantasy1.jpeg'),
    abstract: require('./abstract/Abstract1.jpeg'),
    sculpture: require('./sculpture/Sculpture1.jpeg'),
    modern: require('./modern/Modern1.jpeg'),
    digital: require('./digital/Digital1.jpeg'),
    photography: require('./photography/Photography1.jpeg'),
    llustration: require('./illustration/Illustration1.jpeg'),
    artwork: require('./artwork/img1.jpeg'),
    classic: require('./classic/Classic1.jpeg'),
    logo: require('./logo.png'),
};
